package cleanurl

import "testing"

func Test_www_data_storage_today_com(t *testing.T) {
	urls := map[string]string{
		"http://www.data-storage-today.com/story.xhtml?story_id=89002": "http://www.data-storage-today.com/story.xhtml?story_id=89002",
		"http://www.data-storage-today.com/story.xhtml?story_id=89023": "http://www.data-storage-today.com/story.xhtml?story_id=89023",
		"http://www.data-storage-today.com/story.xhtml?story_id=89010": "http://www.data-storage-today.com/story.xhtml?story_id=89010",
		"http://www.data-storage-today.com/story.xhtml?story_id=89290": "http://www.data-storage-today.com/story.xhtml?story_id=89290",
		"http://www.data-storage-today.com/story.xhtml?story_id=89013": "http://www.data-storage-today.com/story.xhtml?story_id=89013",
		"http://www.data-storage-today.com/story.xhtml?story_id=89107": "http://www.data-storage-today.com/story.xhtml?story_id=89107",
		"http://www.data-storage-today.com/story.xhtml?story_id=89171": "http://www.data-storage-today.com/story.xhtml?story_id=89171",
		"http://www.data-storage-today.com/story.xhtml?story_id=89191": "http://www.data-storage-today.com/story.xhtml?story_id=89191",
		"http://www.data-storage-today.com/story.xhtml?story_id=89394": "http://www.data-storage-today.com/story.xhtml?story_id=89394",
		"http://www.data-storage-today.com/story.xhtml?story_id=88927": "http://www.data-storage-today.com/story.xhtml?story_id=88927",
		"http://www.data-storage-today.com/story.xhtml?story_id=89205": "http://www.data-storage-today.com/story.xhtml?story_id=89205",
		"http://www.data-storage-today.com/story.xhtml?story_id=89326": "http://www.data-storage-today.com/story.xhtml?story_id=89326",
		"http://www.data-storage-today.com/story.xhtml?story_id=89382": "http://www.data-storage-today.com/story.xhtml?story_id=89382",
		"http://www.data-storage-today.com/story.xhtml?story_id=89556": "http://www.data-storage-today.com/story.xhtml?story_id=89556",
		"http://www.data-storage-today.com/story.xhtml?story_id=89585": "http://www.data-storage-today.com/story.xhtml?story_id=89585",
		"http://www.data-storage-today.com/story.xhtml?story_id=88932": "http://www.data-storage-today.com/story.xhtml?story_id=88932",
		"http://www.data-storage-today.com/story.xhtml?story_id=88970": "http://www.data-storage-today.com/story.xhtml?story_id=88970",
		"http://www.data-storage-today.com/story.xhtml?story_id=89072": "http://www.data-storage-today.com/story.xhtml?story_id=89072",
		"http://www.data-storage-today.com/story.xhtml?story_id=88925": "http://www.data-storage-today.com/story.xhtml?story_id=88925",
		"http://www.data-storage-today.com/story.xhtml?story_id=89037": "http://www.data-storage-today.com/story.xhtml?story_id=89037",
		"http://www.data-storage-today.com/story.xhtml?story_id=89128": "http://www.data-storage-today.com/story.xhtml?story_id=89128",
		"http://www.data-storage-today.com/story.xhtml?story_id=89150": "http://www.data-storage-today.com/story.xhtml?story_id=89150",
		"http://www.data-storage-today.com/story.xhtml?story_id=89161": "http://www.data-storage-today.com/story.xhtml?story_id=89161",
		"http://www.data-storage-today.com/story.xhtml?story_id=89167": "http://www.data-storage-today.com/story.xhtml?story_id=89167",
		"http://www.data-storage-today.com/story.xhtml?story_id=89199": "http://www.data-storage-today.com/story.xhtml?story_id=89199",
		"http://www.data-storage-today.com/story.xhtml?story_id=89253": "http://www.data-storage-today.com/story.xhtml?story_id=89253",
		"http://www.data-storage-today.com/story.xhtml?story_id=89302": "http://www.data-storage-today.com/story.xhtml?story_id=89302",
		"http://www.data-storage-today.com/story.xhtml?story_id=89015": "http://www.data-storage-today.com/story.xhtml?story_id=89015",
		"http://www.data-storage-today.com/story.xhtml?story_id=89051": "http://www.data-storage-today.com/story.xhtml?story_id=89051",
		"http://www.data-storage-today.com/story.xhtml?story_id=89132": "http://www.data-storage-today.com/story.xhtml?story_id=89132",
		"http://www.data-storage-today.com/story.xhtml?story_id=89296": "http://www.data-storage-today.com/story.xhtml?story_id=89296",
		"http://www.data-storage-today.com/story.xhtml?story_id=89346": "http://www.data-storage-today.com/story.xhtml?story_id=89346",
		"http://www.data-storage-today.com/story.xhtml?story_id=88930": "http://www.data-storage-today.com/story.xhtml?story_id=88930",
		"http://www.data-storage-today.com/story.xhtml?story_id=89146": "http://www.data-storage-today.com/story.xhtml?story_id=89146",
		"http://www.data-storage-today.com/story.xhtml?story_id=89225": "http://www.data-storage-today.com/story.xhtml?story_id=89225",
		"http://www.data-storage-today.com/story.xhtml?story_id=89339": "http://www.data-storage-today.com/story.xhtml?story_id=89339",
		"http://www.data-storage-today.com/story.xhtml?story_id=89587": "http://www.data-storage-today.com/story.xhtml?story_id=89587",
		"http://www.data-storage-today.com/story.xhtml?story_id=88935": "http://www.data-storage-today.com/story.xhtml?story_id=88935",
		"http://www.data-storage-today.com/story.xhtml?story_id=88943": "http://www.data-storage-today.com/story.xhtml?story_id=88943",
		"http://www.data-storage-today.com/story.xhtml?story_id=89019": "http://www.data-storage-today.com/story.xhtml?story_id=89019",
		"http://www.data-storage-today.com/story.xhtml?story_id=89201": "http://www.data-storage-today.com/story.xhtml?story_id=89201",
		"http://www.data-storage-today.com/story.xhtml?story_id=89235": "http://www.data-storage-today.com/story.xhtml?story_id=89235",
		"http://www.data-storage-today.com/story.xhtml?story_id=89247": "http://www.data-storage-today.com/story.xhtml?story_id=89247",
		"http://www.data-storage-today.com/story.xhtml?story_id=89348": "http://www.data-storage-today.com/story.xhtml?story_id=89348",
		"http://www.data-storage-today.com/story.xhtml?story_id=89566": "http://www.data-storage-today.com/story.xhtml?story_id=89566",
		"http://www.data-storage-today.com/story.xhtml?story_id=88961": "http://www.data-storage-today.com/story.xhtml?story_id=88961",
		"http://www.data-storage-today.com/story.xhtml?story_id=89229": "http://www.data-storage-today.com/story.xhtml?story_id=89229",
		"http://www.data-storage-today.com/story.xhtml?story_id=89412": "http://www.data-storage-today.com/story.xhtml?story_id=89412",
		"http://www.data-storage-today.com/story.xhtml?story_id=89505": "http://www.data-storage-today.com/story.xhtml?story_id=89505",
		"http://www.data-storage-today.com/story.xhtml?story_id=89540": "http://www.data-storage-today.com/story.xhtml?story_id=89540",
		"http://www.data-storage-today.com/story.xhtml?story_id=89586": "http://www.data-storage-today.com/story.xhtml?story_id=89586",
		"http://www.data-storage-today.com/story.xhtml?story_id=88957": "http://www.data-storage-today.com/story.xhtml?story_id=88957",
		"http://www.data-storage-today.com/story.xhtml?story_id=89147": "http://www.data-storage-today.com/story.xhtml?story_id=89147",
		"http://www.data-storage-today.com/story.xhtml?story_id=89148": "http://www.data-storage-today.com/story.xhtml?story_id=89148",
		"http://www.data-storage-today.com/story.xhtml?story_id=89234": "http://www.data-storage-today.com/story.xhtml?story_id=89234",
		"http://www.data-storage-today.com/story.xhtml?story_id=89248": "http://www.data-storage-today.com/story.xhtml?story_id=89248",
		"http://www.data-storage-today.com/story.xhtml?story_id=89385": "http://www.data-storage-today.com/story.xhtml?story_id=89385",
		"http://www.data-storage-today.com/story.xhtml?story_id=89581": "http://www.data-storage-today.com/story.xhtml?story_id=89581",
		"http://www.data-storage-today.com/story.xhtml?story_id=89041": "http://www.data-storage-today.com/story.xhtml?story_id=89041",
		"http://www.data-storage-today.com/story.xhtml?story_id=89046": "http://www.data-storage-today.com/story.xhtml?story_id=89046",
		"http://www.data-storage-today.com/story.xhtml?story_id=89185": "http://www.data-storage-today.com/story.xhtml?story_id=89185",
		"http://www.data-storage-today.com/story.xhtml?story_id=89273": "http://www.data-storage-today.com/story.xhtml?story_id=89273",
		"http://www.data-storage-today.com/story.xhtml?story_id=89001": "http://www.data-storage-today.com/story.xhtml?story_id=89001",
		"http://www.data-storage-today.com/story.xhtml?story_id=89062": "http://www.data-storage-today.com/story.xhtml?story_id=89062",
		"http://www.data-storage-today.com/story.xhtml?story_id=89188": "http://www.data-storage-today.com/story.xhtml?story_id=89188",
		"http://www.data-storage-today.com/story.xhtml?story_id=89189": "http://www.data-storage-today.com/story.xhtml?story_id=89189",
		"http://www.data-storage-today.com/story.xhtml?story_id=88866": "http://www.data-storage-today.com/story.xhtml?story_id=88866",
		"http://www.data-storage-today.com/story.xhtml?story_id=89020": "http://www.data-storage-today.com/story.xhtml?story_id=89020",
		"http://www.data-storage-today.com/story.xhtml?story_id=89232": "http://www.data-storage-today.com/story.xhtml?story_id=89232",
		"http://www.data-storage-today.com/story.xhtml?story_id=89353": "http://www.data-storage-today.com/story.xhtml?story_id=89353",
		"http://www.data-storage-today.com/story.xhtml?story_id=89372": "http://www.data-storage-today.com/story.xhtml?story_id=89372",
		"http://www.data-storage-today.com/story.xhtml?story_id=88924": "http://www.data-storage-today.com/story.xhtml?story_id=88924",
		"http://www.data-storage-today.com/story.xhtml?story_id=89192": "http://www.data-storage-today.com/story.xhtml?story_id=89192",
		"http://www.data-storage-today.com/story.xhtml?story_id=89222": "http://www.data-storage-today.com/story.xhtml?story_id=89222",
		"http://www.data-storage-today.com/story.xhtml?story_id=89344": "http://www.data-storage-today.com/story.xhtml?story_id=89344",
		"http://www.data-storage-today.com/story.xhtml?story_id=89526": "http://www.data-storage-today.com/story.xhtml?story_id=89526",
		"http://www.data-storage-today.com/story.xhtml?story_id=89588": "http://www.data-storage-today.com/story.xhtml?story_id=89588",
		"http://www.data-storage-today.com/story.xhtml?story_id=88953": "http://www.data-storage-today.com/story.xhtml?story_id=88953",
		"http://www.data-storage-today.com/story.xhtml?story_id=88981": "http://www.data-storage-today.com/story.xhtml?story_id=88981",
		"http://www.data-storage-today.com/story.xhtml?story_id=89233": "http://www.data-storage-today.com/story.xhtml?story_id=89233",
	}
	testURLs(t, urls)
}
func Test_www_datacenterknowledge_com(t *testing.T) {
	urls := map[string]string{
		"http://www.datacenterknowledge.com/archives/2013/10/02/bmc-launches-big-data-management-solution-for-hadoop/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                            "http://www.datacenterknowledge.com/archives/2013/10/02/bmc-launches-big-data-management-solution-for-hadoop/",
		"http://www.datacenterknowledge.com/archives/2013/10/03/prudential-digital-realty-deal-could-boost-data-center-investment/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":               "http://www.datacenterknowledge.com/archives/2013/10/03/prudential-digital-realty-deal-could-boost-data-center-investment/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/improving-the-reliability-efficiency-and-effectiveness-of-a-vintage-data-center/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner": "http://www.datacenterknowledge.com/archives/2013/10/10/improving-the-reliability-efficiency-and-effectiveness-of-a-vintage-data-center/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/spectra-logic-devised-deep-storage-tier-vision/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                  "http://www.datacenterknowledge.com/archives/2013/10/10/spectra-logic-devised-deep-storage-tier-vision/",
		"http://www.datacenterknowledge.com/archives/2013/10/11/the-zero-client-the-next-generation-in-client-computing/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                         "http://www.datacenterknowledge.com/archives/2013/10/11/the-zero-client-the-next-generation-in-client-computing/",
		"http://www.datacenterknowledge.com/archives/2013/10/03/diesel-fuel-its-critical-for-standby-power/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                      "http://www.datacenterknowledge.com/archives/2013/10/03/diesel-fuel-its-critical-for-standby-power/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/carter-validus-acquires-att-data-center-facility/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                "http://www.datacenterknowledge.com/archives/2013/10/10/carter-validus-acquires-att-data-center-facility/",
		"http://www.datacenterknowledge.com/archives/2013/10/02/a-closer-look-at-ebays-bloom-powered-data-center/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                "http://www.datacenterknowledge.com/archives/2013/10/02/a-closer-look-at-ebays-bloom-powered-data-center/",
		"http://www.datacenterknowledge.com/archives/2013/10/02/splunk-unlocks-machine-data-analytics-to-broader-audience/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                       "http://www.datacenterknowledge.com/archives/2013/10/02/splunk-unlocks-machine-data-analytics-to-broader-audience/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/cyrusone-seeks-to-bring-online-shopping-to-colocation/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                           "http://www.datacenterknowledge.com/archives/2013/10/10/cyrusone-seeks-to-bring-online-shopping-to-colocation/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/griffin-capital-buys-verizon-wireless-data-center/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                               "http://www.datacenterknowledge.com/archives/2013/10/10/griffin-capital-buys-verizon-wireless-data-center/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/importance-of-designing-seismic-certified-data-centers/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                          "http://www.datacenterknowledge.com/archives/2013/10/10/importance-of-designing-seismic-certified-data-centers/",
		"http://www.datacenterknowledge.com/archives/2013/10/11/interxion-to-build-ninth-frankfurt-data-center/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                  "http://www.datacenterknowledge.com/archives/2013/10/11/interxion-to-build-ninth-frankfurt-data-center/",
		"http://www.datacenterknowledge.com/archives/2013/10/11/taking-your-cloud-deployment-to-the-next-level/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                  "http://www.datacenterknowledge.com/archives/2013/10/11/taking-your-cloud-deployment-to-the-next-level/",
		"http://www.datacenterknowledge.com/archives/2013/10/02/how-to-upgrade-a-data-center-for-efficiency-and-density/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                         "http://www.datacenterknowledge.com/archives/2013/10/02/how-to-upgrade-a-data-center-for-efficiency-and-density/",
		"http://www.datacenterknowledge.com/archives/2013/10/02/more-scenes-from-data-center-world-fall-2013/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                    "http://www.datacenterknowledge.com/archives/2013/10/02/more-scenes-from-data-center-world-fall-2013/",
		"http://www.datacenterknowledge.com/archives/2013/10/02/the-network-is-the-bottleneck-stacks-and-flows-are-the-answer/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                   "http://www.datacenterknowledge.com/archives/2013/10/02/the-network-is-the-bottleneck-stacks-and-flows-are-the-answer/",
		"http://www.datacenterknowledge.com/archives/2013/10/02/video-telecitygroup-opens-helsinki-data-center/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                  "http://www.datacenterknowledge.com/archives/2013/10/02/video-telecitygroup-opens-helsinki-data-center/",
		"http://www.datacenterknowledge.com/archives/2013/10/03/cray-deploys-liquid-cooled-cs300-supercomputer/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                  "http://www.datacenterknowledge.com/archives/2013/10/03/cray-deploys-liquid-cooled-cs300-supercomputer/",
		"http://www.datacenterknowledge.com/archives/2013/10/10/equinix-acquires-key-frankfurt-network-hub/?utm-campaign=Feed%3A+DataCenterKnowledge+%28Data+Center+Knowledge%29&utm-medium=feed&utm-source=feedburner":                                      "http://www.datacenterknowledge.com/archives/2013/10/10/equinix-acquires-key-frankfurt-network-hub/",
	}
	testURLs(t, urls)
}
func Test_www_dotnetcurry_com(t *testing.T) {
	urls := map[string]string{
		"http://www.dotnetcurry.com/ShowArticle.aspx?ID=877": "http://www.dotnetcurry.com/ShowArticle.aspx?ID=877",
		"http://www.dotnetcurry.com/ShowArticle.aspx?ID=889": "http://www.dotnetcurry.com/ShowArticle.aspx?ID=889",
	}
	testURLs(t, urls)
}
func Test_dhbusinessledger_com(t *testing.T) {
	urls := map[string]string{
		"http://dhbusinessledger.com/Main.asp?ArticleID=9332&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9332&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9364&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9364&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9591&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9591&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9884&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9884&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9887&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9887&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9889&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9889&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9480&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9480&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9875&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9875&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9892&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9892&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9906&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9906&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9908&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9908&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9899&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9899&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9903&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9903&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9904&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9904&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9907&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9907&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9363&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9363&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9456&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9456&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9477&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9477&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9586&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9586&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9873&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9873&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9897&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9897&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9544&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9544&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9546&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9546&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9876&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9876&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9909&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9909&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9910&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9910&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9466&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9466&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9872&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9872&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9898&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9898&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9900&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9900&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9911&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9911&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9912&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9912&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9321&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9321&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9888&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9888&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9890&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9890&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9895&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9895&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9914&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9914&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9291&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9291&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9320&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9320&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9871&SectionID=33&SubSectionID=99": "http://dhbusinessledger.com/Main.asp?ArticleID=9871&SectionID=33&SubSectionID=99",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9891&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9891&SectionID=4&SubSectionID=29",
		"http://dhbusinessledger.com/Main.asp?ArticleID=9896&SectionID=4&SubSectionID=29":  "http://dhbusinessledger.com/Main.asp?ArticleID=9896&SectionID=4&SubSectionID=29",
	}
	testURLs(t, urls)
}
