package cleanurl

import "testing"

func Test_www_qas_com(t *testing.T) {
	urls := map[string]string{
		"http://www.qas.com/data-quality-news/american_business_schools_can_bring_big_improvements_to_big_data_9636.htm?urw=":         "http://www.qas.com/data-quality-news/american_business_schools_can_bring_big_improvements_to_big_data_9636.htm",
		"http://www.qas.com/data-quality-news/how_can_data_mining_damage_your_company%27s_integrity_9598.htm?urw=":                    "http://www.qas.com/data-quality-news/how_can_data_mining_damage_your_company%27s_integrity_9598.htm",
		"http://www.qas.com/data-quality-news/retailers_use_big_data_to_pinpoint_their_most_loyal_customers_9645.htm?urw=":            "http://www.qas.com/data-quality-news/retailers_use_big_data_to_pinpoint_their_most_loyal_customers_9645.htm",
		"http://www.qas.com/data-quality-news/tech_sector_must_address_skills_gap_before_tackling_big_data_initiatives_9633.htm?urw=": "http://www.qas.com/data-quality-news/tech_sector_must_address_skills_gap_before_tackling_big_data_initiatives_9633.htm",
		"http://www.qas.com/data-quality-news/corporate_cfos_can_get_more_out_of_big_data_9623.htm?urw=":                              "http://www.qas.com/data-quality-news/corporate_cfos_can_get_more_out_of_big_data_9623.htm",
		"http://www.qas.com/data-quality-news/emphasis_on_data_quality_is_paying_off_9590.htm?urw=":                                   "http://www.qas.com/data-quality-news/emphasis_on_data_quality_is_paying_off_9590.htm",
		"http://www.qas.com/data-quality-news/federal_government_hopes_to_use_more_data_despite_sequester_9618.htm?urw=":              "http://www.qas.com/data-quality-news/federal_government_hopes_to_use_more_data_despite_sequester_9618.htm",
		"http://www.qas.com/data-quality-news/is_data_changing_the_way_we_use_our_office_buildings_9595.htm?urw=":                     "http://www.qas.com/data-quality-news/is_data_changing_the_way_we_use_our_office_buildings_9595.htm",
		"http://www.qas.com/data-quality-news/questions_linger_about_big_data_marketing_9605.htm?urw=":                                "http://www.qas.com/data-quality-news/questions_linger_about_big_data_marketing_9605.htm",
		"http://www.qas.com/data-quality-news/retailers_should_use_more_data_to_improve_their_customer_relationships_9628.htm?urw=":   "http://www.qas.com/data-quality-news/retailers_should_use_more_data_to_improve_their_customer_relationships_9628.htm",
		"http://www.qas.com/data-quality-news/roundup_of_june_news_articles_9597.htm?urw=":                                            "http://www.qas.com/data-quality-news/roundup_of_june_news_articles_9597.htm",
		"http://www.qas.com/data-quality-news/the_big_data_revolution_can_transform_higher_education_9647.htm?urw=":                   "http://www.qas.com/data-quality-news/the_big_data_revolution_can_transform_higher_education_9647.htm",
		"http://www.qas.com/data-quality-news/using_data_for_customer_service_can_be_easy_and_affordable_9634.htm?urw=":               "http://www.qas.com/data-quality-news/using_data_for_customer_service_can_be_easy_and_affordable_9634.htm",
		"http://www.qas.com/data-quality-news/applying_quality_data_to_the_retail_supply_chain_9614.htm?urw=":                         "http://www.qas.com/data-quality-news/applying_quality_data_to_the_retail_supply_chain_9614.htm",
		"http://www.qas.com/data-quality-news/cloud_technologies_improve_the_syncing_of_data_across_platforms_9648.htm?urw=":          "http://www.qas.com/data-quality-news/cloud_technologies_improve_the_syncing_of_data_across_platforms_9648.htm",
		"http://www.qas.com/data-quality-news/ensuring_data_quality_is_difficult_in_healthcare_industry_9642.htm?urw=":                "http://www.qas.com/data-quality-news/ensuring_data_quality_is_difficult_in_healthcare_industry_9642.htm",
		"http://www.qas.com/data-quality-news/how_big_data_can_improve_mobile_e-commerce_9638.htm?urw=":                               "http://www.qas.com/data-quality-news/how_big_data_can_improve_mobile_e-commerce_9638.htm",
		"http://www.qas.com/data-quality-news/information_managers_still_lack_consensus_on_data_quality_9591.htm?urw=":                "http://www.qas.com/data-quality-news/information_managers_still_lack_consensus_on_data_quality_9591.htm",
		"http://www.qas.com/data-quality-news/roundup_of_august_news_articles_9660.htm?urw=":                                          "http://www.qas.com/data-quality-news/roundup_of_august_news_articles_9660.htm",
		"http://www.qas.com/data-quality-news/%27internet_of_things%27_gives_rise_to_era_of_big_data_9657.htm?urw=":                   "http://www.qas.com/data-quality-news/%27internet_of_things%27_gives_rise_to_era_of_big_data_9657.htm",
		"http://www.qas.com/data-quality-news/assuming_data_quality_can_be_risky_for_many_businesses_9624.htm?urw=":                   "http://www.qas.com/data-quality-news/assuming_data_quality_can_be_risky_for_many_businesses_9624.htm",
		"http://www.qas.com/data-quality-news/big_data_can_change_the_way_we_all_do_work_9650.htm?urw=":                               "http://www.qas.com/data-quality-news/big_data_can_change_the_way_we_all_do_work_9650.htm",
		"http://www.qas.com/data-quality-news/companies_struggle_with_various_aspects_of_data_quality_9643.htm?urw=":                  "http://www.qas.com/data-quality-news/companies_struggle_with_various_aspects_of_data_quality_9643.htm",
		"http://www.qas.com/data-quality-news/how_data_analysis_can_improve_customer_service_9622.htm?urw=":                           "http://www.qas.com/data-quality-news/how_data_analysis_can_improve_customer_service_9622.htm",
		"http://www.qas.com/data-quality-news/how_data_changes_the_recruiting_game_9596.htm?urw=":                                     "http://www.qas.com/data-quality-news/how_data_changes_the_recruiting_game_9596.htm",
		"http://www.qas.com/data-quality-news/issues_with_data_quality_lead_to_bounced_emails_9639.htm?urw=":                          "http://www.qas.com/data-quality-news/issues_with_data_quality_lead_to_bounced_emails_9639.htm",
		"http://www.qas.com/data-quality-news/moving_real-time_analytics_from_e-commerce_to_brick-and-mortar_stores_9646.htm?urw=":    "http://www.qas.com/data-quality-news/moving_real-time_analytics_from_e-commerce_to_brick-and-mortar_stores_9646.htm",
		"http://www.qas.com/data-quality-news/overhauling_the_data_center_is_no_easy_process_9654.htm?urw=":                           "http://www.qas.com/data-quality-news/overhauling_the_data_center_is_no_easy_process_9654.htm",
		"http://www.qas.com/data-quality-news/big_data_analytics_will_never_fully_replace_creative_thought_9637.htm?urw=":             "http://www.qas.com/data-quality-news/big_data_analytics_will_never_fully_replace_creative_thought_9637.htm",
		"http://www.qas.com/data-quality-news/businesses_must_invest_in_better_data_storage_resources_9606.htm?urw=":                  "http://www.qas.com/data-quality-news/businesses_must_invest_in_better_data_storage_resources_9606.htm",
		"http://www.qas.com/data-quality-news/data-driven_technologies_can_improve_the_retail_customer_experience_9635.htm?urw=":      "http://www.qas.com/data-quality-news/data-driven_technologies_can_improve_the_retail_customer_experience_9635.htm",
		"http://www.qas.com/data-quality-news/how_data-driven_initiatives_can_reach_mobile_users_9630.htm?urw=":                       "http://www.qas.com/data-quality-news/how_data-driven_initiatives_can_reach_mobile_users_9630.htm",
		"http://www.qas.com/data-quality-news/investing_in_big_data_can_help_improve_corporate_e-commerce_initiatives_9599.htm?urw=":  "http://www.qas.com/data-quality-news/investing_in_big_data_can_help_improve_corporate_e-commerce_initiatives_9599.htm",
		"http://www.qas.com/data-quality-news/big_data_helps_improve_companies%27_workforce_analytics_9586.htm?urw=":                  "http://www.qas.com/data-quality-news/big_data_helps_improve_companies%27_workforce_analytics_9586.htm",
		"http://www.qas.com/data-quality-news/emphasis_on_data_quality_can_improve_corporate_hr_initiatives_9641.htm?urw=":            "http://www.qas.com/data-quality-news/emphasis_on_data_quality_can_improve_corporate_hr_initiatives_9641.htm",
		"http://www.qas.com/data-quality-news/higher_education_still_slow_to_embrace_benefits_of_big_data_9629.htm?urw=":              "http://www.qas.com/data-quality-news/higher_education_still_slow_to_embrace_benefits_of_big_data_9629.htm",
		"http://www.qas.com/data-quality-news/how_data_quality_can_help_craft_the_single-customer_view_9631.htm?urw=":                 "http://www.qas.com/data-quality-news/how_data_quality_can_help_craft_the_single-customer_view_9631.htm",
		"http://www.qas.com/data-quality-news/what_will_be_the_economic_impact_of_the_big_data_movement_9649.htm?urw=":                "http://www.qas.com/data-quality-news/what_will_be_the_economic_impact_of_the_big_data_movement_9649.htm",
		"http://www.qas.com/data-quality-news/3_ways_data_quality_can_benefit_retailers_9627.htm?urw=":                                "http://www.qas.com/data-quality-news/3_ways_data_quality_can_benefit_retailers_9627.htm",
		"http://www.qas.com/data-quality-news/big_data_might_mean_big_savings_for_federal_government_9609.htm?urw=":                   "http://www.qas.com/data-quality-news/big_data_might_mean_big_savings_for_federal_government_9609.htm",
		"http://www.qas.com/data-quality-news/big_data_transforms_public_education_in_colorado_9632.htm?urw=":                         "http://www.qas.com/data-quality-news/big_data_transforms_public_education_in_colorado_9632.htm",
		"http://www.qas.com/data-quality-news/data_analysis_helps_government_with_fraud_prevention_9615.htm?urw=":                     "http://www.qas.com/data-quality-news/data_analysis_helps_government_with_fraud_prevention_9615.htm",
		"http://www.qas.com/data-quality-news/how_can_big_data_lead_to_improvements_in_companies%27_staffs_9600.htm?urw=":             "http://www.qas.com/data-quality-news/how_can_big_data_lead_to_improvements_in_companies%27_staffs_9600.htm",
		"http://www.qas.com/data-quality-news/retailers_must_steer_clear_of_%27creepy%27_big_data_applications_9616.htm?urw=":         "http://www.qas.com/data-quality-news/retailers_must_steer_clear_of_%27creepy%27_big_data_applications_9616.htm",
		"http://www.qas.com/data-quality-news/roundup_of_july_news_articles_9626.htm?urw=":                                            "http://www.qas.com/data-quality-news/roundup_of_july_news_articles_9626.htm",
		"http://www.qas.com/data-quality-news/what_impact_has_data_had_on_business_technology_9601.htm?urw=":                          "http://www.qas.com/data-quality-news/what_impact_has_data_had_on_business_technology_9601.htm",
		"http://www.qas.com/data-quality-news/will_the_education_system_do_more_to_support_data_quality_9621.htm?urw=":                "http://www.qas.com/data-quality-news/will_the_education_system_do_more_to_support_data_quality_9621.htm",
		"http://www.qas.com/data-quality-news/3_big_changes_that_big_data_can_bring_to_healthcare_9610.htm?urw=":                      "http://www.qas.com/data-quality-news/3_big_changes_that_big_data_can_bring_to_healthcare_9610.htm",
		"http://www.qas.com/data-quality-news/education_cios_can_glean_insights_from_working_with_more_data_9612.htm?urw=":            "http://www.qas.com/data-quality-news/education_cios_can_glean_insights_from_working_with_more_data_9612.htm",
		"http://www.qas.com/data-quality-news/emerging_big_data_market_offers_wealth_of_new_job_openings_9655.htm?urw=":               "http://www.qas.com/data-quality-news/emerging_big_data_market_offers_wealth_of_new_job_openings_9655.htm",
		"http://www.qas.com/data-quality-news/how_should_companies_visualize_their_data_9587.htm?urw=":                                "http://www.qas.com/data-quality-news/how_should_companies_visualize_their_data_9587.htm",
		"http://www.qas.com/data-quality-news/is_there_such_a_thing_as_too_much_data_quality_9588.htm?urw=":                           "http://www.qas.com/data-quality-news/is_there_such_a_thing_as_too_much_data_quality_9588.htm",
	}
	testURLs(t, urls)
}
